name: Puzzle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build project
      run: gradle build

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'Puzzle'
        path: build/libs/Puzzle.jar

    - name: Create a release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/distributions/puzzle-game.zip
          build/distributions/puzzle-game.tar